export const departments = [
    "Agriculture, Animal Husbandry & Co-operative",
    "Building Construction",
    "Cabinet Election",
    "Cabinet Secretariat and Vigilance",
    "Commercial Taxes",
    "Drinking Water and Sanitation",
    "Energy",
    "Excise and Prohibition",
    "Finance",
    "Food, Public Distribution & Consumer Affairs",
    "Forest, Environment & Climate Change",
    "Health, Medical Education & Family Welfare",
    "Higher and Technical Education",
    "Home, Jail & Disaster Management",
    "Industries",
    "Information & Public Relations",
    "Information Technology & e-Governance",
    "Labour, Employment, Training and Skill Development",
    "Law",
    "Mines & Geology",
    "Panchayati Raj",
    "Personnel, Administrative Reforms & Rajbhasha",
    "Planning & Development",
    "Revenue, Registration & Land Reforms",
    "Road Construction",
    "Rural Development",
    "Rural Works",
    "Scheduled Tribe, Scheduled Caste, Minority and Backward Class Welfare",
    "School Education & Literacy",
    "Tourism, Arts, Culture, Sports & Youth Affairs",
    "Transport",
    "Urban Development & Housing",
    "Water Resources",
    "Women, Child Development & Social Security",
]